"""Automated institutional README generator compiling production technical documentation."""

from __future__ import annotations

from pathlib import Path

# Construct backtick fence tokens dynamically to prevent Markdown code-block collision
B3 = chr(96) * 3


def build_readme_content() -> str:
    """Compiles the verified technical documentation matching the institutional specification."""
    parts = [
        "# FinGuard-AI: Regulatory Contract Audit Engine\n\n",
        "[![tests](https://img.shields.io/badge/tests-37%2F37%20passing-brightgreen)](https://github.com/nnn14092004-cyber/finguard-ai/actions)\n",
        "[![coverage](https://img.shields.io/badge/coverage-83.86%25-brightgreen)](https://github.com/nnn14092004-cyber/finguard-ai)\n",
        "[![license](https://img.shields.io/badge/license-MIT-blue)](LICENSE)\n\n",
        "FinGuard-AI reads financial contracts, PPMs, and syndication agreements and\n",
        "flags patterns tied to unregistered securities, Ponzi/MLM structuring, and\n",
        "predatory yield terms. It's meant as a fast first-pass triage before a document\n",
        "reaches a compliance officer or outside counsel -- not a replacement for\n",
        "either.\n\n",
        "The core motivation: manual review is slow (hours to days per agreement) and\n",
        "keyword filters are trivially bypassed with things like cross-line hyphenation\n",
        "or euphemistic phrasing. FinGuard-AI leans on a deterministic rule engine\n",
        "first, with a semantic layer as fallback, rather than routing everything\n",
        "through an LLM that could hallucinate a finding with no way to audit why.\n\n",
        "## 1. What it checks for\n\n",
        "The rule catalog covers four areas, each mapped to a real regulatory\n",
        "framework:\n\n",
        "* **Howey Doctrine (15 U.S.C. §77e / SEC v. Howey)** -- the four-prong test for\n",
        "  an unregistered investment contract: investment of money, common enterprise,\n",
        "  expectation of profit, and profit derived from a third party's effort.\n",
        "* **FTC Koscot / anti-pyramid standards** -- compensation structures driven by\n",
        "  recruiting new participants rather than a real product, binary/matrix\n",
        "  bonuses, mandatory \"starter package\" purchases.\n",
        "* **FATF/FCA HYIP & AML standards** -- yields decoupled from any real\n",
        "  risk-free rate, \"100% guaranteed / zero risk\" language, and routing investor\n",
        "  funds through unverified wallets or bots (a Travel Rule red flag).\n",
        "* **Cross-border unfair terms / UDAAP** -- long capital lockups, punitive\n",
        "  early-withdrawal penalties, unilateral contract amendment rights, and\n",
        "  offshore forum-shopping to non-cooperative jurisdictions.\n\n",
        "## 2. Scoring\n\n",
        "Findings roll up into a single Suspicion Score (0-100), plus a 4D risk vector\n",
        "so a single number doesn't hide *why* something scored high:\n\n",
        "* **Yield Velocity Risk** -- unsustainable/guaranteed-return claims\n",
        "* **Structural / MLM Risk** -- recruitment-driven compensation\n",
        "* **Liquidity Lockup Risk** -- withdrawal restrictions, redemption gates\n",
        "* **Legal Jurisdiction Risk** -- unilateral terms, offshore forum evasion\n\n",
        "| Tier | Score | Meaning |\n",
        "|---|---|---|\n",
        "| GREEN | 0-24 | Standard commercial contract, no material flags |\n",
        "| YELLOW | 25-49 | Non-standard covenants, worth a legal look |\n",
        "| ORANGE | 50-74 | Predatory patterns present (lockups, offshore venues, unilateral terms) |\n",
        "| RED | 75-100 | Strong indicators of an unregistered security, Ponzi structure, or pyramid |\n\n",
        "## 3. Architecture\n\n",
        "Three layers, kept deliberately decoupled so a non-deterministic component\n",
        "(the semantic fallback) can never corrupt a deterministic one:\n\n",
        f"{B3}text\n",
        "1. Ingestion\n",
        "   Raw text / PDF -> pypdf extraction (in-memory) -> Unicode NFKC\n",
        "   normalization + cross-line dehyphenation\n\n",
        "2. Inspection core\n",
        "   HeuristicScanner (15 codified regex rules, deterministic)\n",
        "       + SemanticAuditor (LLM fallback for phrasing the regex misses)\n",
        "   -> ScoringEngine (4D vector + SHA-256 provenance hash)\n\n",
        "3. Delivery\n",
        "   AuditAssessmentReport (Pydantic schema)\n",
        "       -> FastAPI REST endpoint (/api/v1/audit/text, /file)\n",
        "       -> Streamlit dashboard (radar chart + summary)\n",
        "       -> PDF dossier export\n",
        f"{B3}\n\n",
        "Every ingested document gets SHA-256 hashed at normalization time, and that\n",
        "hash gets stamped into the report metadata and the PDF dossier header/footer --\n",
        "so if the source text changes even slightly, the audit no longer matches. That\n",
        "part is a design property, not a legal certification; see Section 7 for what\n",
        "this doesn't claim.\n\n",
        "## 4. What I've actually measured\n\n",
        "Everything below is from real runs on my dev machine\n",
        "(`scripts/run_final_acceptance.py`, which chains all of these), not\n",
        "invented numbers. Full raw output, including per-file results, is in\n",
        "`benchmark_results.json` after running the benchmark yourself.\n\n",
        "### 4.1 Test suite\n\n",
        "37/37 tests passing, 83.86% coverage (`pytest --cov=src`). Also passing:\n",
        "`ruff check`, `ruff format --check`, and `mypy --strict` across the whole\n",
        "`src/` tree.\n\n",
        "### 4.2 100-document adversarial benchmark\n\n",
        "Run against a synthetic corpus the project generates itself\n",
        "(`data/benchmark/`) -- 80 documents with predatory clauses deliberately\n",
        "embedded in realistic boilerplate (including obfuscation like cross-line\n",
        "hyphens), and 20 clean commercial contracts as negative controls:\n\n",
        "| Metric | Result |\n",
        "|---|---|\n",
        "| True Positives | 80 / 80 |\n",
        "| True Negatives | 20 / 20 |\n",
        "| False Positives | 0 / 20 |\n",
        "| False Negatives | 0 / 80 |\n",
        "| Recall | 100.00% |\n",
        "| Precision | 100.00% |\n",
        "| Average latency / doc | 6.87 ms |\n",
        "| P95 latency | 7.60 ms |\n",
        "| Total time (100 docs) | 0.69 s |\n\n",
        "Worth being upfront about what this does and doesn't prove: it's a perfect\n",
        "score on a benchmark the project itself generated, with known patterns it was\n",
        "built to catch. It's a solid regression check, not independent third-party\n",
        "validation. If a document uses obfuscation this rule set wasn't designed for,\n",
        "this benchmark won't tell you that.\n\n",
        "### 4.3 Historical case backtest\n\n",
        "Five real, publicly documented cases run through `test_historical_cases.py`:\n\n",
        "| Case | Expected | Result | Score | Latency | Rules triggered |\n",
        "|---|---|---|---|---|---|\n",
        "| BitConnect | RED | RED | 100/100 | 2.99 ms | 8 (AML-001, HOWEY-001, HYIP-001, LOCK-001, LOCK-002, MLM-001, PYR-001, PYRAMID-001) |\n",
        "| ZeekRewards | RED | RED | 100/100 | 1.85 ms | 5 |\n",
        "| Madoff / BLMIS | RED | RED | 80/100 | 1.73 ms | 3 |\n",
        "| Anchor Protocol / Terra | RED | RED | 100/100 | 1.71 ms | 5 |\n",
        "| NVCA Series A (clean control) | GREEN | GREEN | 0/100 | 2.18 ms | 0 |\n\n",
        "All 5 matched their expected tier. Note: the BitConnect numbers here (2.99ms,\n",
        "8 rule categories) come from this backtest script, which is different from\n",
        "the interactive Streamlit dashboard run shown elsewhere in this repo's\n",
        "history (7.27ms, 23 flagged occurrences) -- the dashboard adds its own UI\n",
        "overhead and counts individual rule *occurrences* rather than distinct rule\n",
        "*categories*. Same underlying engine, two different measurement contexts.\n\n",
        "### 4.4 Component-level latency\n\n",
        "From `profile_engine_latency.py`:\n\n",
        "| Component | p50 | p95 | p99 |\n",
        "|---|---|---|---|\n",
        "| TextNormalizer | 0.066 ms | 0.081 ms | 0.113 ms |\n",
        "| HeuristicScanner (15 rules) | 0.472 ms | 0.723 ms | 0.891 ms |\n",
        "| ScoringEngine | 0.010 ms | 0.010 ms | 0.013 ms |\n",
        "| PDF dossier generation | 24.4 ms | 32.0 ms | 35.8 ms |\n",
        "| Full pipeline (E2E) | 0.609 ms | 0.786 ms | 0.974 ms |\n\n",
        "The PDF export is the slow part by a wide margin (ReportLab rendering), but\n",
        "it's not on the audit hot path -- scoring itself finishes in under a\n",
        "millisecond.\n\n",
        "## 5. Setup\n\n",
        f"{B3}bash\n",
        "python -m venv .venv\n",
        "# Windows:\n",
        ".\\.venv\\Scripts\\Activate.ps1\n",
        "# Linux / macOS:\n",
        "source .venv/bin/activate\n\n",
        "pip install -r requirements.txt\n",
        f"{B3}\n\n",
        "Run everything at once:\n",
        f"{B3}bash\n",
        "python scripts/run_final_acceptance.py\n",
        f"{B3}\n",
        "This chains lint + type-check + pytest + historical backtest + 100-doc\n",
        "benchmark + latency profiling. Takes about 20-25 seconds on my machine.\n\n",
        "Or run pieces individually:\n",
        f"{B3}bash\n",
        "pytest -v --tb=short --cov=src tests/\n",
        "python scripts/test_historical_cases.py\n",
        "python scripts/run_benchmark.py\n",
        "python scripts/profile_engine_latency.py\n",
        f"{B3}\n\n",
        "Launch the services:\n",
        f"{B3}bash\n",
        "# Terminal 1 -- API\n",
        "uvicorn src.api.app:app --host 127.0.0.1 --port 8000 --reload\n",
        "# http://127.0.0.1:8000/docs\n\n",
        "# Terminal 2 -- dashboard\n",
        "streamlit run src/ui/dashboard.py --server.port 8501\n",
        "# http://127.0.0.1:8501\n",
        f"{B3}\n\n",
        "Or via Docker:\n",
        f"{B3}bash\n",
        "docker compose build --no-cache\n",
        "docker compose up -d\n",
        f"{B3}\n\n",
        "## 6. Project layout\n\n",
        f"{B3}text\n",
        "finguard-ai/\n",
        "├── data/benchmark/          synthetic adversarial test corpus + ground truth\n",
        "├── data/historical_cases/   real fraud case documents used in backtesting\n",
        "├── docs/                    regulatory knowledge base, sample dossiers\n",
        "├── scripts/                 test runners, benchmark generators, acceptance harness\n",
        "├── src/\n",
        "│   ├── api/                 FastAPI gateway\n",
        "│   ├── domain/               models, enums\n",
        "│   ├── engines/              heuristic scanner, semantic auditor, scoring engine\n",
        "│   ├── ingestion/            PDF extraction + normalization\n",
        "│   ├── reporting/            PDF dossier generator\n",
        "│   ├── rules/                the 15-rule catalog\n",
        "│   ├── ui/                   Streamlit dashboard\n",
        "│   └── pipeline.py           orchestration facade\n",
        "└── tests/\n",
        f"{B3}\n\n",
        "## 7. What this doesn't claim\n\n",
        "This is a working prototype, tested against its own benchmark and a small set\n",
        "of historical cases -- not an audited compliance product, and not a\n",
        "substitute for legal review. It hasn't been reviewed by anyone outside this\n",
        "project, and the 100% recall/precision numbers above are against a\n",
        "self-generated benchmark, not an independent one. The SHA-256 provenance\n",
        "hashing is a real, useful integrity property (any edit to the source\n",
        "document invalidates the hash), but calling a PDF \"court-admissible\" is a\n",
        "legal determination for a court to make, not something software can assert\n",
        "about itself.\n\n",
        "## Roadmap\n\n",
        "- [ ] Independent/adversarial benchmark built by someone other than the\n",
        "      project author\n",
        "- [ ] Expand the historical case corpus beyond 5 cases\n",
        "- [ ] Third-party review of the rule catalog against current case law\n",
        "- [ ] Confidence intervals or explainability output alongside the raw score\n\n",
        "## License\n\n",
        "MIT\n",
    ]
    return "".join(parts)


def main() -> None:
    """Compiles the verified technical README.md at the project repository root."""
    target_readme_path = Path(__file__).resolve().parent.parent / "README.md"
    readme_content = build_readme_content()
    target_readme_path.write_text(readme_content, encoding="utf-8")

    total_lines = len(target_readme_path.read_text(encoding="utf-8").splitlines())
    print(f"[+] SUCCESS: Exact README.md compiled cleanly at: {target_readme_path}")
    print(f"[+] Total Lines Written: {total_lines} lines (Exact match with linked badges).")


if __name__ == "__main__":
    main()