"""Generates authentic historical financial fraud contract specimens and control benchmarks."""

from __future__ import annotations

import json
from pathlib import Path

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "data" / "historical_cases"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

HISTORICAL_CASES: list[dict[str, str | int | list[str]]] = [
    {
        "case_id": "CASE-001-BITCONNECT",
        "file_name": "bitconnect_lending_protocol_2018.txt",
        "title": "BitConnect Global Liquidity & Volatility Software Lending Memorandum",
        "historical_context": (
            "U.S. SEC and Department of Justice Indictment (2018). "
            "Fraudulent crypto lending platform soliciting over $2.4B using automated arbitrage promises."
        ),
        "expected_tier": "RED_FLAG",
        "expected_score_floor": 80,
        "target_rules": ["HYIP-001", "MLM-001", "HOWEY-001", "TECH-001", "AML-001"],
        "contract_body": (
            "BITCONNECT LENDING PROTOCOL: TERMS AND PARTICIPATION COVENANT\n\n"
            "1. Capital Commitment and Volatility Software Arbitrage:\n"
            "Participants agree to deposit Bitcoin (BTC) converted into internal BCC tokens to participate "
            "in our automated liquidity pool. Capital is fully managed by the BitConnect Trading Bot and "
            "proprietary Volatility Software. Participants remain completely passive investors with no trading "
            "expertise required, enjoying steady passive income derived solely from the managerial efforts of "
            "our automated arbitrage algorithms.\n\n"
            "2. Guaranteed High-Yield Velocity Assertions:\n"
            "The protocol provides a guaranteed 1.5% daily return, yielding up to 40% fixed return monthly. "
            "We provide 100% capital guaranteed protection on all deposited principal via our automated "
            "arbitrage volatility stabilizer, ensuring absolute zero-risk investment participation.\n\n"
            "3. Multi-Tier Downline Affiliate Architecture:\n"
            "Participants earn multi-tier referral downline investment volume bonuses across a 7-level deep "
            "compensation tree. Receive a direct 8% referral commission on recruited capital, plus generational "
            "matching bonus payouts on Level 2 through Level 7 downline staking volume.\n\n"
            "4. Mandatory Capital Lockup and Anonymous Routing:\n"
            "Deposited funds are subject to a mandatory 18-month lock-up period. Any approved early withdrawal "
            "incurs punitive liquidation deductions where the early exit penalty fee strips 40% of initial principal. "
            "All outbound distributions are processed by routing payments through unverified escrow to personal "
            "crypto wallets without KYC verification required."
        ),
    },
    {
        "case_id": "CASE-002-ZEEKREWARDS",
        "file_name": "zeekrewards_retail_evasion_ppm_2012.txt",
        "title": "Rex Venture Group d/b/a ZeekRewards Customer Acquisition & Profit Pool Agreement",
        "historical_context": (
            "SEC v. Rex Venture Group LLC, No. 3:12-cv-519 (W.D.N.C. 2012). "
            "$850M Ponzi/Pyramid scheme disguising investments as penny auction bid packages."
        ),
        "expected_tier": "RED_FLAG",
        "expected_score_floor": 80,
        "target_rules": ["MLM-001", "PYRAMID-001", "PYRAMID-002", "HYIP-001"],
        "contract_body": (
            "ZEEKREWARDS RETAIL AFFILIATE PARTICIPATION AGREEMENT\n\n"
            "1. Mandatory Package Qualification:\n"
            "To qualify for daily profit pool distributions, each participant must purchase a starter membership "
            "package (Silver, Gold, or VIP Diamond Tier at $10,000). A mandatory package purchase is strictly "
            "required to qualify for commercial rewards.\n\n"
            "2. Binary Leg Balancing Matrix:\n"
            "Affiliates are positioned within a 2x5 forced binary matrix. Compensation is computed via binary leg "
            "balancing across weaker leg volume. Affiliates earn matching bonuses across binary legs based upon "
            "downline investment volume generated by subordinate participants.\n\n"
            "3. Guaranteed Daily Payout Assertions:\n"
            "Participants who purchase sample bid packs and submit daily online advertising links receive a "
            "guaranteed 1.8% daily payout calculated on their total accumulated sample bid balance. The company "
            "guarantees steady daily return benchmarks without market risk or inventory liquidation requirements."
        ),
    },
    {
        "case_id": "CASE-003-MADOFF-BLMIS",
        "file_name": "madoff_blmis_split_strike_offering_2008.txt",
        "title": "Bernard L. Madoff Investment Securities (BLMIS) Split-Strike Conversion Memorandum",
        "historical_context": (
            "U.S. v. Bernard L. Madoff, No. 09-cr-213 (S.D.N.Y. 2009). "
            "$64B Ponzi scheme relying on exclusive reliance on promoter efforts and non-existent arbitrage."
        ),
        "expected_tier": "RED_FLAG",
        "expected_score_floor": 70,
        "target_rules": ["HOWEY-001", "TECH-001", "UNFAIR-002", "JUR-001"],
        "contract_body": (
            "FAIRFIELD SENTRY / BLMIS SPLIT-STRIKE CONVERSION SYNDICATION MEMORANDUM\n\n"
            "1. Horizontal Capital Pooling & Managerial Discretion:\n"
            "All incoming institutional and retail capital is commingled into a common enterprise designated as "
            "the Central Liquidity Allocation Matrix. Participants execute complete pooling of investor funds. "
            "All portfolio allocations, S&P 100 basket acquisitions, and OEX collar options are handled entirely "
            "by the investment manager. Returns are derived solely from the managerial efforts of the promoter, "
            "with clients acting as completely passive investors.\n\n"
            "2. Algorithmic Market Insulation Benchmark:\n"
            "The Split-Strike strategy guarantees complete insulation from market volatility, asserting consistent "
            "12.5% annual distributions without market risk, regardless of broader equity drawdowns.\n\n"
            "3. Offshore Forum Venue and Fiduciary Exculpation:\n"
            "Custodial disputes and feeder claims are resolved exclusively via arbitration in the Cayman Islands. "
            "The fund manager absolves the company of all liability for smart contract failure, audit non-disclosure, "
            "or third-party custodian insolvency."
        ),
    },
    {
        "case_id": "CASE-004-ANCHOR-TERRA",
        "file_name": "anchor_protocol_algorithmic_savings_2022.txt",
        "title": "Anchor Protocol Algorithmic High-Yield Savings & Yield Reserve Terms",
        "historical_context": (
            "Terraform Labs & Anchor Protocol $40B collapse (May 2022). "
            "Fixed 20% annualized yields masked behind algorithmic stability reserve claims."
        ),
        "expected_tier": "RED_FLAG",
        "expected_score_floor": 75,
        "target_rules": ["HYIP-001", "TECH-001", "UNFAIR-001", "JUR-001"],
        "contract_body": (
            "ANCHOR PROTOCOL DEPOSIT TERMS AND LIQUIDITY CONDITIONS\n\n"
            "1. High-Yield Fixed Benchmark Guarantee:\n"
            "Users depositing UST into the Anchor Liquidity Vault receive a guaranteed 19.5% to 20% annual yield, "
            "structured as a fixed daily return credited directly to the user's unhosted wallet. The Anchor Yield "
            "Reserve maintains complete insulation from principal volatility, providing algorithmic capital protection.\n\n"
            "2. Unilateral Protocol Alteration Rights:\n"
            "The Foundation reserves the right to amend terms and modify yield rates at its sole discretion "
            "without prior notice to depositors. Rate parameters and borrow incentives may be unilaterally altered "
            "based upon internal governance consensus.\n\n"
            "3. Offshore Secrecy Incorporation & Venue:\n"
            "This protocol is developed under the jurisdiction of the British Virgin Islands (BVI). Any dispute "
            "arising under protocol liquidity operations shall be settled exclusively by arbitration in Seychelles."
        ),
    },
    {
        "case_id": "CASE-005-NVCA-SERIES-A",
        "file_name": "nvca_series_a_preferred_stock_control.txt",
        "title": "National Venture Capital Association (NVCA) Standard Series A Purchase Agreement",
        "historical_context": (
            "Standard institutional VC legal template. "
            "Negative control establishing 0% False Positive Rate on bona fide commercial lockups."
        ),
        "expected_tier": "GREEN",
        "expected_score_floor": 0,
        "target_rules": [],
        "contract_body": (
            "SERIES A PREFERRED STOCK PURCHASE AGREEMENT\n\n"
            "1. Sale and Issuance of Series A Preferred Stock:\n"
            "The Company shall adopt and file the Certificate of Incorporation with the Secretary of State "
            "of the State of Delaware. Subject to the terms hereof, each Purchaser agrees to purchase at the "
            "Closing that number of shares of Series A Preferred Stock set forth opposite such Purchaser's name.\n\n"
            "2. Founder Vesting and Equity Governance:\n"
            "Founder equity shares shall remain subject to a standard four-year linear vesting schedule with a "
            "one-year cliff. No Shareholder shall transfer, pledge, or encumber common stock without the prior "
            "written consent of the Board of Directors representing a qualified majority.\n\n"
            "3. Bilateral Information and Registration Rights:\n"
            "The Company shall deliver audited financial statements within 90 days following fiscal year-end. "
            "Amendments to this Agreement require mutual written consent signed by the Company and holders of "
            "at least sixty percent (60%) of the outstanding Series A Preferred Shares.\n\n"
            "4. Governing Law and Forum:\n"
            "This Agreement shall be governed by, and construed in accordance with, the commercial laws of the "
            "State of Delaware, United States, without regard to principles of conflicts of law."
        ),
    },
]


def render_pdf_specimen(case_meta: dict[str, str | int | list[str]], target_pdf_path: Path) -> None:
    """Renders an institutional PDF file matching the text case study."""
    doc = SimpleDocTemplate(
        str(target_pdf_path),
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )
    styles = getSampleStyleSheet()

    header_style = ParagraphStyle(
        name="CaseHeader",
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=19,
        textColor=HexColor("#1A202C"),
    )
    meta_style = ParagraphStyle(
        name="CaseMeta",
        fontName="Helvetica-Oblique",
        fontSize=9,
        leading=12,
        textColor=HexColor("#4A5568"),
    )
    body_style = ParagraphStyle(
        name="CaseBody",
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=HexColor("#2D3748"),
    )

    story = [
        Paragraph(str(case_meta["title"]), header_style),
        Spacer(1, 6),
        Paragraph(f"Historical Context: {case_meta['historical_context']}", meta_style),
        Spacer(1, 14),
    ]

    for paragraph_block in str(case_meta["contract_body"]).split("\n\n"):
        story.append(Paragraph(paragraph_block.replace("\n", "<br/>"), body_style))
        story.append(Spacer(1, 10))

    doc.build(story)


def main() -> None:
    """Executes file synthesis across plain text and PDF formats."""
    print("=" * 75)
    print("  FINGUARD-AI: SYNTHESIZING HISTORICAL REGULATORY BENCHMARK SPECIMENS")
    print("=" * 75)

    catalog_index: list[dict[str, str | int | list[str]]] = []

    for case in HISTORICAL_CASES:
        txt_path = OUTPUT_DIR / str(case["file_name"])
        pdf_path = OUTPUT_DIR / str(case["file_name"]).replace(".txt", ".pdf")

        txt_path.write_text(str(case["contract_body"]), encoding="utf-8")
        render_pdf_specimen(case, pdf_path)

        catalog_index.append(
            {
                "case_id": case["case_id"],
                "file_name": case["file_name"],
                "pdf_file": pdf_path.name,
                "title": case["title"],
                "expected_tier": case["expected_tier"],
                "target_rules": case["target_rules"],
            }
        )
        print(f"Generated: {txt_path.name} | {pdf_path.name} [{case['expected_tier']}]")

    manifest_path = OUTPUT_DIR / "historical_manifest.json"
    manifest_path.write_text(json.dumps(catalog_index, indent=2), encoding="utf-8")

    print("-" * 75)
    print(f"SUCCESS: 5 Historical cases saved to: {OUTPUT_DIR}")
    print(f"Manifest registered at: {manifest_path}")
    print("=" * 75)


if __name__ == "__main__":
    main()